# unifdef -DZOPFLI_CACHE_LENGTH=8 -DZOPFLI_HASH_SAME -DZOPFLI_HASH_SAME_HASH -DZOPFLI_HAS_BUILTIN_CLZ -DZOPFLI_LAZY_MATCHING -D__has_builtin -DZOPFLI_MASTER_BLOCK_SIZE=1000000 -DZOPFLI_MAX_CHAIN_HITS=8192 -DZOPFLI_SHORTCUT_LONG_REPETITIONS -DZOPFLI_WINDOW_SIZE=32768 -U_WIN32 -U__cplusplus

In [1]: a = !ls *.h

In [2]: for i in a:
   ...:     !unifdef -DZOPFLI_CACHE_LENGTH=8 -DZOPFLI_HASH_SAME -DZOPFLI_HASH_SAME_HASH -DZOPFLI_HAS_BUILTIN_CLZ -DZOPFLI_LAZY_MATCHING -D
   ...: __has_builtin -DZOPFLI_MASTER_BLOCK_SIZE=1000000 -DZOPFLI_MAX_CHAIN_HITS=8192 -DZOPFLI_SHORTCUT_LONG_REPETITIONS -DZOPFLI_WINDOW_S
   ...: IZE=32768 -U_WIN32 -U__cplusplus {i} -o {i}
   ...: 

In [3]: a = !ls *.c

In [4]: for i in a:
   ...:     !unifdef -DZOPFLI_CACHE_LENGTH=8 -DZOPFLI_HASH_SAME -DZOPFLI_HASH_SAME_HASH -DZOPFLI_HAS_BUILTIN_CLZ -DZOPFLI_LAZY_MATCHING -D
   ...: __has_builtin -DZOPFLI_MASTER_BLOCK_SIZE=1000000 -DZOPFLI_MAX_CHAIN_HITS=8192 -DZOPFLI_SHORTCUT_LONG_REPETITIONS -DZOPFLI_WINDOW_S
   ...: IZE=32768 -U_WIN32 -U__cplusplus {i} -o {i}
   ...: 